project:
  type: website

website:
  title: "Statistik Stadt Zürich"
  navbar:
    background: "#0F05A0"
    foreground: "white"
    left:
      - href: index.qmd
        text: Home

format:
  html:
    css: sszTheme.css
    

